name: paloma_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6


  #Architecture Packages
  sqflite: ^2.3.3                         #SQLite
  mobx: ^2.2.0                            #для стейтменеджмента
  flutter_mobx: ^2.0.6+5                  #для стейтменеджмента
  auto_route: ^7.9.1                      #для навигации между страницами
  dio: ^5.1.1                             #для REST/CURL запросов
  http: ^1.2.0                            #для REST/CURL запросов фотографий
  http_parser: ^4.0.2                     #для парса mime типов при загрузке фото
  retrofit: ^4.0.3                        #для упрощенной разработки запросов на основе dio/http
  web_socket_channel: ^2.4.0              #для чатов на websocket-ах
  socket_io_client: ^2.0.3+1              #для чатов на websocket-ах
  json_annotation: ^4.8.1                 #для генерации моделей и dto
  freezed_annotation: ^2.4.1              #для генерации моделей и dto
  auto_mappr_annotation: ^2.1.0           #для сопоставления моделей к dto

  #UI Packages
  palette_generator: ^0.3.3+3             #для подбора цветовой палитры
  another_flushbar: ^1.12.30              #для показа кастомных боттом баров
  rflutter_alert: ^2.0.7                  #для отображения диалоговых окон
  flutter_svg: ^2.0.7                     #для векторных изображений
  cached_network_image: ^3.3.1            #для загрузки фото по url с кэшированием внутри приложения
  blur: ^3.1.0                            #для blur эффекта

  #Feature Packages
  webview_flutter: ^4.6.0

dev_dependencies:
  build_runner: ^2.4.6                    #для кодогенерации
  mobx_codegen: ^2.1.1                    #для кодогенерации стейт-менеджеров
  auto_route_generator: ^7.3.2            #для кодогенерации навигации
  auto_mappr: ^2.1.1                      #для кодогенерации сопоставителей dto к моделям
  json_serializable: ^6.7.1               #для кодогенерации моделей и dto
  freezed: ^2.4.1                         #для кодогенерации моделей и dto
  retrofit_generator: ^8.0.5              #для кодогенерации REST/CURL запросов
  flutter_lints: ^2.0.0                   #линтер
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: comfortaa
      fonts:
        - asset: assets/fonts/comfortaa/comfortaa.ttf
    - family: comfortaa_bold
      fonts:
        - asset: assets/fonts/comfortaa/static/comfortaa_bold.ttf
    - family: comfortaa_light
      fonts:
        - asset: assets/fonts/comfortaa/static/comfortaa_light.ttf
    - family: comfortaa_medium
      fonts:
        - asset: assets/fonts/comfortaa/static/comfortaa_medium.ttf
    - family: comfortaa_regular
      fonts:
        - asset: assets/fonts/comfortaa/static/comfortaa_regular.ttf
    - family: comfortaa_semibold
      fonts:
        - asset: assets/fonts/comfortaa/static/comfortaa_semibold.ttf
    - family: dela_gothic_one
      fonts:
        - asset: assets/fonts/dela_gothic_one/dela_gothic_one.ttf
    - family: jetbrains_mono
      fonts:
        - asset: assets/fonts/jetbrains_mono/jetbrains_mono.ttf